Repository S-O-O-P/S-O-O-P-BackEnd, pull requests merged in 2024-07, with the labels that each got.

#3 [FEATURE][SECURITY] 백엔드 에서 프론트로 넘길때 Redirect 부분 (수정필요)
  src/main/java/com/soop/jwtsecurity/config/CorsMvcConfig.java
  src/main/java/com/soop/jwtsecurity/config/SecurityConfig.java
  src/main/java/com/soop/jwtsecurity/controller/LogoutController.java
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTFilter.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTUtil.java
  src/main/java/com/soop/jwtsecurity/mapper/UserMapper.java
  src/main/resources/mapper/UserMapper.xml
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#6 [FEATURE][CS][MAIN] 고객섹터 메인
  http/CsMain.http
  src/main/java/com/soop/jwtsecurity/controller/MainController.java
  src/main/java/com/soop/pages/customerservice/controller/CustomerServiceController.java
  src/main/java/com/soop/pages/customerservice/model/dao/CustomerServiceMapper.java
  src/main/java/com/soop/pages/customerservice/model/dto/FileDTO.java
  src/main/java/com/soop/pages/customerservice/model/dto/InquiryDTO.java
  src/main/java/com/soop/pages/customerservice/model/dto/MemberDTO.java
  src/main/java/com/soop/pages/customerservice/model/dto/NoticeDTO.java
  src/main/java/com/soop/pages/customerservice/model/dto/NoticeMemberDTO.java
  src/main/java/com/soop/pages/customerservice/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/customerservice/model/service/CustomerServiceService.java
  src/main/resources/mapper/CustomerServiceMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: :pager: BackEnd

#8 [FEATURE][NOTICEDETAIL] 공지사항 상세페이지 백엔드
  http/CsMain.http
  src/main/java/com/soop/pages/customerservice/controller/CustomerServiceController.java
  src/main/java/com/soop/pages/customerservice/model/dao/CustomerServiceMapper.java
  src/main/java/com/soop/pages/customerservice/model/dto/NoticeMemberDTO.java
  src/main/java/com/soop/pages/customerservice/model/service/CustomerServiceService.java
  src/main/resources/mapper/CustomerServiceMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#11 [FEATURE][INQUIRY] 1:1문의 작성 프론트 연결 DB 저장
  http/CsMain.http
  src/main/java/com/soop/pages/customerservice/controller/CustomerServiceController.java
  src/main/java/com/soop/pages/customerservice/model/dao/CustomerServiceMapper.java
  src/main/java/com/soop/pages/customerservice/model/dto/InquiryMemberDTO.java
  src/main/java/com/soop/pages/customerservice/model/service/CustomerServiceService.java
  src/main/resources/mapper/CustomerServiceMapper.xml
Labels: 📬 API, :pager: BackEnd

#15 [FEATURE][HONEYPOT][DETAIL] BACKEND
  http/Honeypot.http
  src/main/java/com/soop/pages/honeypot/controller/HoneyPotController.java
  src/main/java/com/soop/pages/honeypot/model/dao/HoneyPotMapper.java
  src/main/java/com/soop/pages/honeypot/model/dto/ApplicationDTO.java
  src/main/java/com/soop/pages/honeypot/model/dto/ApprovalStatusDTO.java
  src/main/java/com/soop/pages/honeypot/model/dto/CommentAndLinkBeeUserDTO.java
  src/main/java/com/soop/pages/honeypot/model/dto/CommentDTO.java
  src/main/java/com/soop/pages/honeypot/model/dto/HoneypotAndApplicationAndApprovalStatusDTO.java
  src/main/java/com/soop/pages/honeypot/model/dto/HoneypotDTO.java
  src/main/java/com/soop/pages/honeypot/model/service/HoneyPotService.java
  src/main/resources/mapper/HoneyPotMapper.xml
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#13 [FEATURE][SECURITY] Connect DataBase
  README.md
  src/main/java/com/soop/jwtsecurity/config/SecurityConfig.java
  src/main/java/com/soop/jwtsecurity/controller/MyController.java
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/controller/SignUpController.java
  src/main/java/com/soop/jwtsecurity/dto/CustomOAuth2User.java
  src/main/java/com/soop/jwtsecurity/dto/GoogleResponse.java
  src/main/java/com/soop/jwtsecurity/dto/KakaoResponse.java
  src/main/java/com/soop/jwtsecurity/dto/NaverResponse.java
  src/main/java/com/soop/jwtsecurity/dto/OAuth2Response.java
  src/main/java/com/soop/jwtsecurity/dto/UserDTO.java
  src/main/java/com/soop/jwtsecurity/entityDTO/RefreshEntity.java
  src/main/java/com/soop/jwtsecurity/entityDTO/UserEntity.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTFilter.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTUtil.java
  src/main/java/com/soop/jwtsecurity/mapper/UserMapper.java
  src/main/java/com/soop/jwtsecurity/service/CustomOAuth2UserService.java
  src/main/resources/mapper/UserMapper.xml
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#19 [FEATURE][CULTUREINFO][RESTAPI]
  src/main/java/com/soop/pages/cultureinfo/controller/CultureInfoController.java
  src/main/java/com/soop/pages/cultureinfo/model/dao/CultureInfoMapper.java
  src/main/java/com/soop/pages/cultureinfo/model/dto/CultureInfoDTO.java
  src/main/java/com/soop/pages/cultureinfo/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/cultureinfo/model/service/CultureInfoService.java
  src/main/resources/mapper/CultureInfoMapper.xml
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#21 [FEATURE][MYPAGE][BACKEND]
  http/MyPage.http
  src/main/java/com/soop/pages/config/Application.java
  src/main/java/com/soop/pages/honeypot/controller/HoneyPotController.java
  src/main/java/com/soop/pages/honeypot/model/dao/HoneyPotMapper.java
  src/main/java/com/soop/pages/honeypot/model/service/HoneyPotService.java
  src/main/java/com/soop/pages/mypage/controller/MyPageController.java
  src/main/java/com/soop/pages/mypage/model/dao/MyPageMapper.java
  src/main/java/com/soop/pages/mypage/model/dto/EvaluateUserRatingDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/FinishedHoneypotDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/InterestDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/MyCommentDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/MyHoneypotDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/MyInquiryDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/ParticipatingHoneypotDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/RatingDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/UserProfileDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/UserProfileUpdateDTO.java
  src/main/java/com/soop/pages/mypage/model/dto/UserRatingDTO.java
  src/main/java/com/soop/pages/mypage/model/service/MyPageService.java
  src/main/resources/mapper/CultureInfoMapper.xml
  src/main/resources/mapper/HoneyPotMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#25 [FEATURE][HONEYPONEYPOTANDMYPAGE][BACKEND2]
  http/Honeypot.http
  http/MyPage.http
  src/main/java/com/soop/jwtsecurity/dto/NaverResponse.java
  src/main/java/com/soop/pages/honeypot/controller/HoneyPotController.java
  src/main/java/com/soop/pages/honeypot/model/dao/HoneyPotMapper.java
  src/main/java/com/soop/pages/honeypot/model/service/HoneyPotService.java
  src/main/java/com/soop/pages/mypage/controller/MyPageController.java
  src/main/java/com/soop/pages/mypage/model/dao/MyPageMapper.java
  src/main/java/com/soop/pages/mypage/model/service/MyPageService.java
  src/main/resources/mapper/HoneyPotMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: ✨ Feature

#24 [FEATURE] [SECURITY] cookies 에 access 토큰(개인 정보 포함) 발급
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/controller/SignUpController.java
  src/main/java/com/soop/jwtsecurity/controller/UserController.java
  src/main/java/com/soop/jwtsecurity/dto/CustomOAuth2User.java
  src/main/java/com/soop/jwtsecurity/dto/InterestAndInterestOfuserDTO.java
  src/main/java/com/soop/jwtsecurity/entityDTO/UserEntity.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTFilter.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTUtil.java
  src/main/java/com/soop/jwtsecurity/mapper/UserMapper.java
  src/main/java/com/soop/jwtsecurity/service/CustomOAuth2UserService.java
  src/main/java/com/soop/pages/cultureinfo/controller/CultureInfoController.java
  src/main/resources/mapper/UserMapper.xml
Labels: 📬 API, ✨ Feature

#27 [FEATURE][INTEREST,USERCODE] 회원 관심사 저장, 회원 번호 TOKEN에 담기
  src/main/java/com/soop/jwtsecurity/config/SecurityConfig.java
  src/main/java/com/soop/jwtsecurity/controller/LogoutController.java
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/controller/SignUpController.java
  src/main/java/com/soop/jwtsecurity/dto/UserDTO.java
  src/main/java/com/soop/jwtsecurity/dto/UserSignUpDTO.java
  src/main/java/com/soop/jwtsecurity/entityDTO/RefreshEntity.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTFilter.java
  src/main/java/com/soop/jwtsecurity/mapper/UserMapper.java
  src/main/resources/mapper/UserMapper.xml
Labels: 📬 API, ✨ Feature

#32 [FEATURE][HONEYPOT][MYPAGE][FIX]
  http/Honeypot.http
  http/MyPage.http
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/pages/honeypot/controller/HoneyPotController.java
  src/main/java/com/soop/pages/honeypot/model/dao/HoneyPotMapper.java
  src/main/java/com/soop/pages/honeypot/model/service/HoneyPotService.java
  src/main/java/com/soop/pages/mypage/controller/MyPageController.java
  src/main/java/com/soop/pages/mypage/model/dao/MyPageMapper.java
  src/main/java/com/soop/pages/mypage/model/dto/MyInquiryDTO.java
  src/main/java/com/soop/pages/mypage/model/service/MyPageService.java
  src/main/resources/mapper/HoneyPotMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: ✨ Feature, 🔨 Refactor

#28 [FEATURE][LOGIN] Refreshed AccessToken
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTUtil.java
Labels: 📬 API, ✨ Feature

#31 [FEATURE][CULTUREINFO][RESTAPI] 얼리버드 공연/전시 정보 가격정보 NaN 표시 에러 및 RESTAPI 호출 URL 수정
  src/main/java/com/soop/pages/cultureinfo/controller/CultureInfoController.java
  src/main/resources/mapper/CultureInfoMapper.xml
Labels: 📬 API, 🐞 BugFix, ✨ Feature, :pager: BackEnd

#34 [FEATURE][MYPAGE][PROFILEPIC] 프로필 수정 클라우드 활용으로 리팩토링
  build.gradle
  http/MyPage.http
  src/main/java/com/soop/pages/firebase/config/FirebaseConfig.java
  src/main/java/com/soop/pages/firebase/service/FileUploadService.java
  src/main/java/com/soop/pages/mypage/controller/MyPageController.java
  src/main/java/com/soop/pages/mypage/model/dao/MyPageMapper.java
  src/main/java/com/soop/pages/mypage/model/service/MyPageService.java
Labels: 📬 API, ✨ Feature, :pager: BackEnd, ⚙ Setting

#35 [FEATURE][NOTICE] 공지사항 정렬
  src/main/java/com/soop/pages/customerservice/controller/CustomerServiceController.java
  src/main/java/com/soop/pages/customerservice/model/dto/FileDTO.java
  src/main/resources/mapper/CustomerServiceMapper.xml
Labels: :pager: BackEnd

#37 [FATURE][NOTICE] 공지사항 이미지 파이어베이스
  src/main/java/com/soop/pages/customerservice/controller/CustomerServiceController.java
  src/main/java/com/soop/pages/customerservice/model/dao/CustomerServiceMapper.java
  src/main/java/com/soop/pages/customerservice/model/service/CustomerServiceService.java
  src/main/resources/mapper/CustomerServiceMapper.xml
Labels: 📬 API, :pager: BackEnd

#38 [FEATURE][CULTUREINFO][SWAGGER] 공연/전시 정보 REST API - SWAGGER 등록 작업
  build.gradle
  src/main/java/com/soop/pages/cultureinfo/controller/CultureInfoController.java
  src/main/java/com/soop/swagger/SwaggerConfig.java
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#40 [REFACTOR][JWTSECURITY] 엑세스토큰 정보에 ProfilePic 정보 추가
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTUtil.java
Labels: 🔨 Refactor

#42 [REFACTOR][EDITPROFILE] 토큰 재발급 시 프로필 사진 호출
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/entityDTO/RefreshEntity.java
  src/main/java/com/soop/jwtsecurity/mapper/UserMapper.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🔨 Refactor

#44 [FEATURE][HONEYPOT][SWAGGER] 마이페이지, 허니팟 Swagger 등록 완료
  src/main/java/com/soop/pages/honeypot/controller/HoneyPotController.java
  src/main/java/com/soop/pages/mypage/controller/MyPageController.java
Labels: 🔨 Refactor

#45 [FEATURE][MAIN][MODIFY] 메인 페이지에 회원의 관심사 정보 조회 REST API 추가
  src/main/java/com/soop/pages/main/controller/MainController.java
  src/main/java/com/soop/pages/main/model/dao/MainMapper.java
  src/main/java/com/soop/pages/main/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/main/model/service/MainService.java
  src/main/resources/mapper/MainMapper.xml
Labels: 📬 API, ✨ Feature, :pager: BackEnd

#48 [FEATURE][GLOBALEXCEPTION] 클라이언트 예외처리
  build.gradle
  src/main/java/com/soop/jwtsecurity/config/ForbiddenException.java
  src/main/java/com/soop/jwtsecurity/config/GlobalExceptionHandler.java
Labels: ✨ Feature, :pager: BackEnd

#49 [FEATURE][SECURITY] SWAGGER 작성
  src/main/java/com/soop/jwtsecurity/config/CorsMvcConfig.java
  src/main/java/com/soop/jwtsecurity/config/SecurityConfig.java
  src/main/java/com/soop/jwtsecurity/controller/LogoutController.java
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/controller/SignUpController.java
  src/main/java/com/soop/jwtsecurity/dto/CustomOAuth2User.java
  src/main/java/com/soop/jwtsecurity/dto/GoogleResponse.java
  src/main/java/com/soop/jwtsecurity/dto/InterestAndInterestOfuserDTO.java
  src/main/java/com/soop/jwtsecurity/dto/KakaoResponse.java
  src/main/java/com/soop/jwtsecurity/dto/NaverResponse.java
  src/main/java/com/soop/jwtsecurity/dto/OAuth2Response.java
  src/main/java/com/soop/jwtsecurity/dto/UserSignUpDTO.java
  src/main/java/com/soop/jwtsecurity/entityDTO/RefreshEntity.java
  src/main/java/com/soop/jwtsecurity/entityDTO/UserEntity.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTFilter.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTUtil.java
  src/main/java/com/soop/jwtsecurity/mapper/UserMapper.java
  src/main/java/com/soop/jwtsecurity/service/CustomOAuth2UserService.java
Labels: 📃 Docs

#57 [FEATURE][MYPAGE][HONEYPOT][REFACTOR] 마이페이지 유저평가 중복여부 확인 API 추가
  http/MyPage.http
  src/main/java/com/soop/pages/mypage/controller/MyPageController.java
  src/main/java/com/soop/pages/mypage/model/dao/MyPageMapper.java
  src/main/java/com/soop/pages/mypage/model/service/MyPageService.java
  src/main/resources/mapper/MyPageMapper.xml
Labels: 📬 API, :pager: BackEnd, 🔨 Refactor

#54 [FEATURE][GLOBALEXCEPTION2] 예외처리 수정
  src/main/java/com/soop/jwtsecurity/config/GlobalExceptionHandler.java
  src/main/java/com/soop/pages/honeypot/controller/HoneyPotController.java
Labels: ✨ Feature, :pager: BackEnd

#55 [FEATURE][NOTICE] 정렬 수정
  src/main/resources/mapper/CustomerServiceMapper.xml
Labels: :pager: BackEnd

#58 [FEATURE][SIGNUP] Refactor
  src/main/java/com/soop/jwtsecurity/config/CorsMvcConfig.java
  src/main/java/com/soop/jwtsecurity/controller/MainController.java
  src/main/java/com/soop/jwtsecurity/controller/ReissueController.java
  src/main/java/com/soop/jwtsecurity/controller/SignUpController.java
  src/main/java/com/soop/jwtsecurity/controller/UserController.java
  src/main/java/com/soop/jwtsecurity/dto/UserSignUpDTO.java
  src/main/java/com/soop/jwtsecurity/handler/CustomSuccessHandler.java
  src/main/java/com/soop/jwtsecurity/jwt/JWTUtil.java
  src/main/java/com/soop/jwtsecurity/mapper/UserMapper.java
  src/main/java/com/soop/jwtsecurity/service/CustomOAuth2UserService.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🔨 Refactor
